version: '3.7'

services:
  rdf-differ-api:
    container_name: rdf-differ-api
    image: meaningfy/rdf-differ-api:latest
    ports:
      - ${RDF_DIFFER_API_PORT}:${RDF_DIFFER_API_PORT}
    env_file: .env
    restart: always
    networks:
      - mydefault

  rdf-differ-ui:
    container_name: rdf-differ-ui
    image: meaningfy/rdf-differ-ui:latest
    ports:
      - ${RDF_DIFFER_UI_PORT}:${RDF_DIFFER_UI_PORT}
    env_file: .env
    restart: always
    networks:
      - mydefault

  rdf-differ-fuseki:
    container_name: rdf-differ-fuseki
    image: meaningfy/fuseki:latest
    volumes:
      - rdf-differ-fuseki:/fuseki
    env_file: .env
    restart: always
    environment:
      - ADMIN_PASSWORD=${RDF_DIFFER_FUSEKI_ADMIN_PASSWORD}
      - JVM_ARGS=${RDF_DIFFER_FUSEKI_JVM_ARGS}
    ports:
      - ${RDF_DIFFER_FUSEKI_PORT}:3030
    networks:
      - mydefault

  rdf-validator-api:
    container_name: rdf-validator-api
    image: meaningfy/rdf-validator-api:latest
    ports:
      - ${VALIDATOR_API_PORT}:${VALIDATOR_API_PORT}
    env_file: .env
    restart: always
    networks:
      - mydefault

  rdf-validator-ui:
    container_name: rdf-validator-ui
    image: meaningfy/rdf-validator-ui:latest
    ports:
      - ${VALIDATOR_UI_PORT}:${VALIDATOR_UI_PORT}
    env_file: .env
    restart: always
    depends_on:
      - "rdf-validator-api"
    networks:
      - mydefault

  splash-page:
    container_name: splash-page
    image: meaningfy/splash-nginx:latest
    ports:
      - 80:80
    volumes:
      - ./splash-nginx:/usr/share/nginx/html
    env_file: .env
    restart: always
    networks:
      - mydefault

  jenkins-automation:
    container_name: jenkins-automation
    image: jenkins/jenkins:latest
    ports:
      - ${JENKINS_UI_PORT}:8080
      - ${JENKINS_AGENTS_PORT}:50000
    env_file: .env
    restart: always
    volumes:
      - jenkins-home:/var/jenkins_home
    privileged: true
    networks:
      - mydefault

#LinekdPipes ETL service suite

  linkedpipes-etl-storage:
    container_name: linkedpipes-etl-storage
    image: meaningfy/linkedpipes-etl-storage:latest
    ports:
      - ${LP_ETL_STORAGE_PORT}:${LP_ETL_STORAGE_PORT}
    env_file: .env
    environment:
      - LP_ETL_DOMAIN=${LP_ETL_DOMAIN}
    restart: always
    volumes:
      - linkedpipes-logs:/data/lp/etl/logs
      - linkedpipes-data-storage:/data/lp/etl/storage
      - type: volume
        source: linkedpipes-configuration
        target: /data/lp/etl/configuration
        read_only: true
        volume:
          nocopy: true
    networks:
      - mydefault

  linkedpipes-etl-executor:
    container_name: linkedpipes-etl-executor
    image: meaningfy/linkedpipes-etl-executor:latest
    ports:
      - ${LP_ETL_EXECUTOR_PORT}:${LP_ETL_EXECUTOR_PORT}
    env_file: .env
    environment:
      - LP_ETL_DOMAIN=${LP_ETL_DOMAIN}
    restart: always
    volumes:
      - linkedpipes-data-execution:/data/lp/etl/executor
      - linkedpipes-logs:/data/lp/etl/logs
      - type: volume
        source: linkedpipes-configuration
        target: /data/lp/etl/configuration
        read_only: true
        volume:
          nocopy: true
    networks:
      - mydefault

  linkedpipes-etl-executor-monitor:
    container_name: linkedpipes-etl-executor-monitor
    image: meaningfy/linkedpipes-etl-executor-monitor:latest
    ports:
      - ${LP_ETL_MONITOR_PORT}:${LP_ETL_MONITOR_PORT}
      - 2221:2221
      - 2222:2222
      - 2225:2225
    env_file: .env
    environment:
      - LP_ETL_DOMAIN=${LP_ETL_DOMAIN}
    restart: always
    volumes:
      - linkedpipes-data-execution:/data/lp/etl/executor
      - linkedpipes-logs:/data/lp/etl/logs
      - type: volume
        source: linkedpipes-configuration
        target: /data/lp/etl/configuration
        read_only: true
        volume:
          nocopy: true
    networks:
      - mydefault

  linkedpipes-etl-frontend:
    container_name: linkedpipes-etl-frontend
    image: meaningfy/linkedpipes-etl-frontend:latest
    ports:
      - ${LP_ETL_PORT}:${LP_ETL_PORT}
    env_file: .env
    environment:
      - LP_ETL_DOMAIN=${LP_ETL_DOMAIN}
    restart: always
    volumes:
      - linkedpipes-logs:/data/lp/etl/logs
      - type: volume
        source: linkedpipes-configuration
        target: /data/lp/etl/configuration
        read_only: true
        volume:
          nocopy: true
    networks:
      - mydefault

  linkedpipes-fuseki:
    container_name: linkedpipes-fuseki
    image: meaningfy/fuseki:latest
    volumes:
      - linkedpipes-fuseki:/fuseki
    env_file: .env
    restart: always
    environment:
      - ADMIN_PASSWORD=${LP_ETL_FUSEKI_ADMIN_PASSWORD}
      - JVM_ARGS=${LP_ETL_FUSEKI_JVM_ARGS}
    ports:
      - ${LP_ETL_FUSEKI_PORT}:3030
    networks:
      - mydefault

  rdf-fingerprinter-api:
    container_name: rdf-fingerprinter-api
    image: meaningfy/rdf-fingerprinter-api:latest
    ports:
      - ${RDF_FINGERPRINTER_API_PORT}:${RDF_FINGERPRINTER_API_PORT}
    env_file: .env
    restart: always
    networks:
      - mydefault

  rdf-fingerprinter-ui:
    container_name: rdf-fingerprinter-ui
    image: meaningfy/rdf-fingerprinter-ui:latest
    ports:
      - ${RDF_FINGERPRINTER_UI_PORT}:${RDF_FINGERPRINTER_UI_PORT}
    env_file: .env
    depends_on:
      - "rdf-fingerprinter-api"
    restart: always
    networks:
      - mydefault

  rdf-fingerprinter-fuseki:
    container_name: rdf-fingerprinter-fuseki
    image: meaningfy/fuseki:latest
    env_file:
      - .env
    environment:
      - ADMIN_PASSWORD=${RDF_FINGERPRINTER_FUSEKI_ADMIN_PASSWORD}
      - JVM_ARGS=${RDF_FINGERPRINTER_FUSEKI_JVM_ARGS}
    ports:
      - ${RDF_FINGERPRINTER_FUSEKI_PORT}:3030
    volumes:
          - rdf-fingerprinter-fuseki:/fuseki
    networks:
      - mydefault

#Camunda

  camunda:
    container_name: camunda
    image: camunda/camunda-bpm-workbench:latest
    ports:
      - ${CAMUNDA_UI_PORT}:8080
    volumes:
    - rdf-camunda:/camunda/conf/
    networks:
      - mydefault

volumes:
  rdf-camunda:
  jenkins-home:
  rdf-differ-fuseki:
  rdf-fingerprinter-fuseki:
  linkedpipes-fuseki:
  linkedpipes-logs:
  linkedpipes-data-execution:
  linkedpipes-data-storage:
  linkedpipes-configuration:
    name: linkedpipes-configuration
    external: true

networks:
  mydefault:
    name: globalnet