name: package and deploy

on:
  release:
    types: [published]

jobs:
  main:
    name: main
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Set basic env
        run: |
          echo "DKR_HUB_URL_FUSEKI=meaningfy/fuseki" >> $GITHUB_ENV
          echo "DKR_HUB_URL_SPLASH_NGINX=meaningfy/splash-nginx" >> $GITHUB_ENV
          echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
          echo "DATE_TIME=$(date -d "-4 hours" "+%Y-%m-%d_%HH%Ms%S")" >> $GITHUB_ENV

      - name: Set tagset env
        run: |
          # logically defined tags
          echo "TAG_LATEST_FUSEKI=$DKR_HUB_URL_FUSEKI:latest" >> $GITHUB_ENV
          echo "TAG_LATEST_SPLASH_NGINX=$DKR_HUB_URL_SPLASH_NGINX:latest" >> $GITHUB_ENV
          echo "TAG_VERSION_FUSEKI=$DKR_HUB_URL_FUSEKI:$RELEASE_VERSION" >> $GITHUB_ENV
          echo "TAG_VERSION_SPLASH_NGINX=$DKR_HUB_URL_SPLASH_NGINX:$RELEASE_VERSION" >> $GITHUB_ENV

      - name: Build
        run: |
          docker build --tag $TAG_LATEST_FUSEKI --tag $TAG_VERSION_FUSEKI --file ./docker/fuseki/Dockerfile  .
          docker build --tag $TAG_LATEST_SPLASH_NGINX --tag $TAG_VERSION_SPLASH_NGINX --file ./docker/splash-nginx/Dockerfile  .

      - name: Logs / docker (inspect, history, version, info), uname
        run: |
          docker inspect $TAG_LATEST_FUSEKI
          docker history $TAG_LATEST_FUSEKI --human --no-trunc
          docker inspect $TAG_LATEST_SPLASH_NGINX
          docker history $TAG_LATEST_SPLASH_NGINX --human --no-trunc
          docker version
          docker info
          uname -a

      - name: Publish on Docker hub
        run: |
          echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login --username ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
          docker push $TAG_LATEST_FUSEKI
          docker push $TAG_VERSION_FUSEKI
          docker push $TAG_LATEST_SPLASH_NGINX
          docker push $TAG_VERSION_SPLASH_NGINX
